### ISSUE TITLE
Add a 'measured area' in import striatum/POA & calculate 'estimated numbers'

### ISSUE THREAD

**Issue by CecileBridlance** [NicolleLouis/microglia_data#11]
For Striatum and POA : add new field 'measured area' (present in the csv, see example).
This is the measured area of the whole structure. 'area' only corresponds to the area of quantification => used to calculate density from the Ki+ and Ki-. 
Now with the density and the measured area, we can estimate the number of microglia in the whole structure : 
estimated_Ki_pos=density_Ki_pos*Measured_area
estimated_Ki_neg=density_Ki_neg*Measured_area
When doing the export, possibility to choose numbers or estimated numbers 
If 'measured area' is empty, then estimated_Ki_pos=Ki_pos

**Comment by CecileBridlance** [comment]
Density is calculated from updated numbers and area of quantification => not good.
Either calculated with ki pos/neg and area of quantification OR updated ki pos/neg and area

**Comment by NicolleLouis** [comment]
Done, je dois je dois faire la meme chose pour la taille des slices? (La je calcule la density post changement avec la slice thickness)

**Comment by NicolleLouis** [comment]
Done
